name: installation test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: prepare conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: see phtread
        shell: bash -l {0}
        run: ldconfig -p | grep pthread
      - name: run script
        shell: bash -l {0}
        run: python install_psbody.py --verbose
